#include "script_component.hpp"
#include "..\script_macros.hpp"

class CfgPatches
{
	class ADDON
	{
		name = COMPONENT_NAME;
		version = VERSION;
		units[] = {};
		weapons[] = {};
		requiredVersion = REQ_VERSION;
		requiredAddons[] =
		{
			"a3_data_f",
			"a3_weapons_f",
			"a3_weapons_f_aaf",
			"a3_weapons_f_acc",
			"a3_weapons_f_ammoboxes",
			"a3_weapons_f_beta",
			"a3_weapons_f_beta_acc",
			"a3_weapons_f_beta_ammoboxes",
			"a3_weapons_f_beta_ebr",
			"a3_weapons_f_beta_longrangerifles_ebr",
			"a3_weapons_f_beta_longrangerifles_gm6",
			"a3_weapons_f_beta_longrangerifles_m320",
			"a3_weapons_f_beta_rifles_khaybar",
			"a3_weapons_f_beta_rifles_mx",
			"a3_weapons_f_beta_rifles_trg20",
			"a3_weapons_f_bootcamp",
			"a3_weapons_f_bootcamp_ammoboxes",
			"a3_weapons_f_bootcamp_longrangerifles_gm6",
			"a3_weapons_f_bootcamp_longrangerifles_gm6_camo",
			"a3_weapons_f_bootcamp_longrangerifles_m320",
			"a3_weapons_f_bootcamp_longrangerifles_m320_camo",
			"a3_weapons_f_csat",
			"a3_weapons_f_dummyweapons",
			"a3_weapons_f_ebr",
			"a3_weapons_f_epa",
			"a3_weapons_f_epa_acc",
			"a3_weapons_f_epa_ammoboxes",
			"a3_weapons_f_epa_ebr",
			"a3_weapons_f_epa_longrangerifles_dmr_01",
			"a3_weapons_f_epa_longrangerifles_gm6",
			"a3_weapons_f_epa_rifles_mx",
			"a3_weapons_f_epb",
			"a3_weapons_f_epb_acc",
			"a3_weapons_f_epb_ammoboxes",
			"a3_weapons_f_epb_longrangerifles_gm3",
			"a3_weapons_f_epb_longrangerifles_gm6",
			"a3_weapons_f_epb_longrangerifles_m320",
			"a3_weapons_f_epb_rifles_mx_black",
			"a3_weapons_f_epc",
			"a3_weapons_f_exp",
			"a3_weapons_f_exp_launchers_rpg32",
			"a3_weapons_f_exp_launchers_rpg7",
			"a3_weapons_f_exp_launchers_titan",
			"a3_weapons_f_exp_longrangerifles_dmr_07",
			"a3_weapons_f_exp_machineguns_lmg_03",
			"a3_weapons_f_exp_pistols_pistol_01",
			"a3_weapons_f_exp_rifles_ak12",
			"a3_weapons_f_exp_rifles_akm",
			"a3_weapons_f_exp_rifles_aks",
			"a3_weapons_f_exp_rifles_arx",
			"a3_weapons_f_exp_rifles_ctar",
			"a3_weapons_f_exp_rifles_ctars",
			"a3_weapons_f_exp_rifles_spar_01",
			"a3_weapons_f_exp_rifles_spar_02",
			"a3_weapons_f_exp_rifles_spar_03",
			"a3_weapons_f_exp_smgs_smg_05",
			"a3_weapons_f_explosives",
			"a3_weapons_f_fia",
			"a3_weapons_f_gamma",
			"a3_weapons_f_gamma_acc",
			"a3_weapons_f_gamma_ammoboxes",
			"a3_weapons_f_gamma_items",
			"a3_weapons_f_gamma_longrangerifles_ebr",
			"a3_weapons_f_gamma_rifles_mx",
			"a3_weapons_f_headgear",
			"a3_weapons_f_itemholders",
			"a3_weapons_f_items",
			"a3_weapons_f_kart",
			"a3_weapons_f_kart_pistols_pistol_signal_f",
			"a3_weapons_f_launchers_law",
			"a3_weapons_f_launchers_nlaw",
			"a3_weapons_f_launchers_rpg32",
			"a3_weapons_f_launchers_titan",
			"a3_weapons_f_longrangerifles_dmr_01",
			"a3_weapons_f_longrangerifles_ebr",
			"a3_weapons_f_longrangerifles_gm6",
			"a3_weapons_f_longrangerifles_m320",
			"a3_weapons_f_machineguns_m200",
			"a3_weapons_f_machineguns_zafir",
			"a3_weapons_f_mark",
			"a3_weapons_f_mark_acc",
			"a3_weapons_f_mark_ebr",
			"a3_weapons_f_mark_longrangerifles_dmr_01",
			"a3_weapons_f_mark_longrangerifles_dmr_02",
			"a3_weapons_f_mark_longrangerifles_dmr_03",
			"a3_weapons_f_mark_longrangerifles_dmr_04",
			"a3_weapons_f_mark_longrangerifles_dmr_05",
			"a3_weapons_f_mark_longrangerifles_dmr_06",
			"a3_weapons_f_mark_longrangerifles_ebr",
			"a3_weapons_f_mark_longrangerifles_gm6",
			"a3_weapons_f_mark_longrangerifles_gm6_camo",
			"a3_weapons_f_mark_longrangerifles_m320",
			"a3_weapons_f_mark_longrangerifles_m320_camo",
			"a3_weapons_f_mark_machineguns_m200",
			"a3_weapons_f_mark_machineguns_mmg_01",
			"a3_weapons_f_mark_machineguns_mmg_02",
			"a3_weapons_f_mark_machineguns_zafir",
			"a3_weapons_f_mark_rifles_khaybar",
			"a3_weapons_f_mark_rifles_mk20",
			"a3_weapons_f_mark_rifles_mx",
			"a3_weapons_f_mark_rifles_sdar",
			"a3_weapons_f_mark_rifles_trg20",
			"a3_weapons_f_nato",
			"a3_weapons_f_pistols_acpc2",
			"a3_weapons_f_pistols_p07",
			"a3_weapons_f_pistols_pdw2000",
			"a3_weapons_f_pistols_pistol_heavy_01",
			"a3_weapons_f_pistols_pistol_heavy_02",
			"a3_weapons_f_pistols_rook40",
			"a3_weapons_f_rifles_khaybar",
			"a3_weapons_f_rifles_mk20",
			"a3_weapons_f_rifles_mx",
			"a3_weapons_f_rifles_mx_black",
			"a3_weapons_f_rifles_sdar",
			"a3_weapons_f_rifles_smg_02",
			"a3_weapons_f_rifles_trg20",
			"a3_weapons_f_rifles_vector",
			"a3_weapons_f_smgs_pdw2000",
			"a3_weapons_f_smgs_smg_01",
			"a3_weapons_f_smgs_smg_02"
		};
		author = AUTHOR;
		authors[] =
		{
			"Whigital"
		};
		magazines[] = {};
		ammo[] = {};
	};
};
